skip_tests: true
bootstrap_timezone: Etc/UTC
bootstrap_distribution: talos
bootstrap_schematic_id: "aa1bd3013a4f46e7cce4af9ad6d9a297b123f74bc4b1d57ffdee0b0e05ba215e"
bootstrap_node_network: "192.168.100.0/23"
bootstrap_node_default_gateway: 192.168.100.1
bootstrap_node_inventory:
  - name: "talos1"
    address: "192.168.101.22"
    controller: true
    talos_disk: /dev/sda
    talos_nic: BC:24:11:B1:5B:44
  - name: "talos2"
    address: "192.168.101.23"
    controller: true
    talos_disk: /dev/sda
    talos_nic: BC:24:11:8D:02:38
  - name: "talos3"
    address: "192.168.101.24"
    controller: true
    talos_disk: /dev/sda
    talos_nic: BC:24:11:3E:0D:98
  - name: "talos4"
    address: "192.168.101.25"
    controller: false
    talos_disk: /dev/sda
    talos_nic: BC:24:11:6C:A2:45
  - name: "talos5"
    address: "192.168.101.26"
    controller: false
    talos_disk: /dev/sda
    talos_nic: BC:24:11:0D:1B:3C
  - name: "talos6"
    address: "192.168.101.27"
    controller: false
    talos_disk: /dev/sda
    talos_nic: BC:24:11:00:80:E0
bootstrap_dns_servers: ["1.1.1.1", "1.0.0.1"]
bootstrap_search_domain: "."
bootstrap_github_private_key: "github-deploy-key"
bootstrap_pod_network: 10.69.0.0/16
bootstrap_service_network: 10.96.0.0/16
bootstrap_controllers_vip: 192.168.101.254
bootstrap_ntp_servers: time.cloudflare.com
bootstrap_endpoint: "192.168.101.254"
bootstrap_tls_sans: ["192.168.101.252", "*.fuzzywumpkins", "192.168.101.253", "192.168.101.254"]
bootstrap_sops_age_pubkey: "age1ypwm874ugwyxfzyzkzuq79qcs04nwdjnkje622xxl5e4yg9nny6q4qc8qf"
bootstrap_bgp:
  enabled: false
bootstrap_github_address: https://github.com/acarter-ims/klustersOriginal.git
bootstrap_github_branch: main
bootstrap_github_webhook_token: 32696440b9654f7dab22e88b88e165d0
bootstrap_cloudflare:
  enabled: true
  domain: wakkalabs.com
  token: FP3XeDOaEjhCRCZWZzeZxPBp4wEFMZMbdLDEUxjC
  acme:
    email: austin.carter2689@gmail.com
    production: true
  ingress_vip: 192.168.101.252
  gateway_vip: 192.168.101.253
  tunnel:
    id: 3fc55099-997c-473b-b10f-0d286015c540
    account_id: 6713ee5c4a16f5773ab80feea8189140
    secret: J2TbUSidf+c1C68YiiDwaaFvVvFrulI5fr7hZrmuW7E=
    ingress_vip: 192.168.101.251
