apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Jy12M/A8a4JJBb+ZZuzgw9wPOd2GI+aCMd4qwTCdUES9vYoi,iv:lzePNtq8qemW6iNy71eVGoccuiGCqKkv4FiTcGBqsWc=,tag:Ht+nAzNaRMqePY7r0EVicQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:UY7oB10zAF2QlSkdVrRdp+CV3/uDY46yAQ3f9ldHUUP37H+vNsLnf/ydjdCwEnTey7zDFkpq6x71FZEitS46ij6lmPA/qHc182+QTty0ruIux7qrjGX/EZeXSKcBsvnxH0jGu2RmRav6/yeH60wIOoctWx+/bYwNLstpMmRVORNiJAph4PnshK6qprobPHmjmNKWcvJSzBSFlImwsSBx+8ufhLDmX2wwvGwq3IPkzg==,iv:/UTMcYATMYYOOUPMSWWL3zpdcXeZyq/6103pUr05VSU=,tag:CH/RcDZiIuA8LHhiODN3Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ypwm874ugwyxfzyzkzuq79qcs04nwdjnkje622xxl5e4yg9nny6q4qc8qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WlVzQ2dWWjNEWW5XSUVm
            M1JYdTZFT1ltWitjUXRjTlJjcUgvVTdwKzFFCmhJOXU4L2RVb2hNR2VEbG9UU2FM
            SjBTQUZxajNDd3h6bGVmZjg1Ukx0bFUKLS0tIGQ0UE5jQlhkWXliVmFoSHNLQjYy
            L1VpeW5EekpHN2J1eTZrTnhTTytHZmsKxqx5ysCJ62XT/le0qdFm8EDB6eABtV8I
            gO8UtUz3hJJTAtwvUGtaAsZ9odQUFL48GgX0Mj2W0hRJMal4Wc1rEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T23:04:35Z"
    mac: ENC[AES256_GCM,data:h2YVPzB4hQW2qrjNEx2CVoXnbxjhDRkeEuBM+w+SmGe+O4/3ygky1KNSLyDfCgm/qmEiJsx5ujTBBxNvUgtwvQMQHGRiOdA0HhrD7mTixdRP1MIKERxkW1V2cIr2z2ZqXlYL0BJDXqkUdWRf4LTNnAxG7OU/AiJMjkogxGwJ6qg=,iv:vQeB9L8auQnvpcmXMCnJgARbi+n0SzpM+aIqRexW0mU=,tag:RAy6aOi6ICefSuTy7t61VA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
