apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ufX/bBhjg0B+KsKIN8KUfx4I7b1R1gQ7o1aW55+qQ4uShhbbvTy13A==,iv:DgEk9AyLhaNNawaPY24+SZ20mt89ZEQD8+ijo0x2dIs=,tag:z8d3UFtroIVnR6VGpzqxCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ypwm874ugwyxfzyzkzuq79qcs04nwdjnkje622xxl5e4yg9nny6q4qc8qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZW5ldDU3dmxKUDJxQ0hu
            UndrSWJrTHpldVlWZkU5OUZBZjZaVkxOdkhzCnFSQko0eFRYcWVIVHduV3h2Y1FR
            bEJYbHpKZFUzTXRaemR0ak5WYXVvcFEKLS0tIDYyOVF3Y2VzNi8zZFpZRWRtL090
            eXVQK2dpZUNsN1lKN2Qxdk54aXNSOHMKBGYAE6jPcrMS4NnLG58JnaTjq6qp7Mpz
            fdyftJa5mOjvcTX68BD9N5bFfAS7Kf+CtDH/fsHghv/Vd23dXgSV6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T23:04:35Z"
    mac: ENC[AES256_GCM,data:n1iF4BYpuJdGse0Zr52ROvxzHkRyWIv0RKbFdy/1d2sDxYy37ybDLae3aJyVsQlFwfN2tuBSu3YU3uqPM0kgRFac+21zd3LYDQJyoAVfhqOI/H3D45xRQ9oCYF48zmK5n4829mZBHiRHgPUf6UyCN1Z1nVOvfPCZ/ckHy2BPCew=,iv:S2nZNZPEecap6Ux9F7/az8Dd5B8ewkj6QAz3rEyabvk=,tag:hY4ocF4GWNOcQmiTFQYn5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
