apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:kjW6gxQdI8Ub7Y7MFDqCZT3OlaXYjLHNNToYhG/m/WA=,iv:9Nhm+Ymw3L3zIZf/eewNL1jGiCGVzdS/7vWdJylR2Nw=,tag:FPkedMl74i3KSspSpOsA2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ypwm874ugwyxfzyzkzuq79qcs04nwdjnkje622xxl5e4yg9nny6q4qc8qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TFBFSG9hRUFmQnBkeVB3
            MVJUUHF1a3lleTVNUGFtVm0waUt6a25hMlg4CjhQNHg1NktaVDdUdUVjZ0FzRFpC
            eHhVdFA4VUFUZ1hGS1Y1UnplbS91S0UKLS0tIEFLMmMyTDVCK1lMSkVZYlRnb2tl
            eFlmYXp6VGl1a3hjR2FzK1U0TTVzRTAKAtRmF5ihfngvTwXejI9WzwecTQglsv/B
            k8Ug8E6UkPlYiBv+Z1bXHaNuYfKkeUiZqdwFM2ggKHo0S33ITnjz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T23:04:35Z"
    mac: ENC[AES256_GCM,data:BcAYcddUh5pbmHB7IiHtI03Lhix8xHTH3ISWocPYF8Kg0nTmWkolAa8coAiw2OIjDn7E25FeIVGd4AIU9zHjJoLX1/kmmGTBG8wc/OlECZh3EOMxh1l93gAMIf+FwNuvbCjE4xyVI6vU2F5TOzi54SPOQttqEwqNu5rdrH3o79c=,iv:31NXpMUQun4KBlki0YPyn+vwfZgZ6vwkagV/S/Bfq3A=,tag:zM28WtZ50OF2bHUHWaG/Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
