apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:trxZ75Kn3q/8An8BTAD19s82mShHryGV/qO8SARz0KE=,iv:WW2Ykk9wL4KpxdW3FL9voGLhKKa9pfGVpXAviSRF7wg=,tag:HSGYyGucG0x/YPYSkPOqgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ypwm874ugwyxfzyzkzuq79qcs04nwdjnkje622xxl5e4yg9nny6q4qc8qf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTGhmNVJTall0eDF1YnNK
            cXlPM1I4VXl4OGtCaVg5Sm9oZUMyUnNyclFZCm41M0d4V3YycXdnalhNbloxQkcy
            aFZRYUJWaGsrQTB5WjFnSklsNDhGRjgKLS0tIFJ2bFE4ZHNEazdVWW55MWJpZEJG
            NjJwanRtZjVxMHFaQ202TkVGUGRYV28KT4cE5OhJwUVGpzyetKg1lTC8urLfbHvk
            UD0HrZ7j9HLLe1wLXMM3OWv1hHYjcVObaRU2Nd7NTh4WP+6fQaC9Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T02:00:23Z"
    mac: ENC[AES256_GCM,data:nw8JhleMu026d+lTDyC+VIkJZn5Hs3rejaLh+FUAJVeWf6UtbdDvjxRWRUpc+qgKtmW/YTBqbIFdmfiXlxvQ6sQb5CSkoN2+N4W3ooWGF1RLICslIjgEek4G6TH/HOhZYSsiRzlP5KkMF4fsH04+I9v7xVgiXi4XJUPYKhfNUq8=,iv:OB0n/rLJSgGUAm75CU8RfVZybNBtOWVyP9O+C5I9S3E=,tag:TfwTpQP1rfG1PatXlr2cUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
